function plotcube(size, origin, alpha, color)
    % 绘制三维长方体辅助函数
    vertices = [...
        origin; ...
        origin + [size(1) 0 0]; ...
        origin + [size(1) size(2) 0]; ...
        origin + [0 size(2) 0]; ...
        origin + [0 0 size(3)]; ...
        origin + [size(1) 0 size(3)]; ...
        origin + [size(1) size(2) size(3)]; ...
        origin + [0 size(2) size(3)]; ...
    ];
    
    faces = [...
        1 2 3 4; ...
        5 6 7 8; ...
        1 2 6 5; ...
        2 3 7 6; ...
        3 4 8 7; ...
        4 1 5 8; ...
    ];
    
    patch('Vertices', vertices, 'Faces', faces, ...
          'FaceColor', color, 'FaceAlpha', alpha, ...
          'EdgeColor', 'none');
end